lib/main.dart, lib/ui/screens/settings_screen.dart
Closes #151.
Moves the About card in settings down to the bottom.
This makes the SettingsCubit not lazy, so that notifications will practically always be loaded before showing the setting screen, removing a flashy change when it's finished loading.
=> Move About card to bottom

lib/ui/screens/food_screen.dart
Closes #158.
Sorry @Jorritboer I stole your issue just to have something to do.
Removes the pizza icon and adds ellipsis to food product names. In case of ellipsis, the price is removed first, but with the icon removed it's unlikely that ellipsis occur at all.
=> Fix pizza name overflow

ios/Runner/Info.plist, lib/ui/screens/event_screen.dart
This opens maps directly on  iOS, instead of via the browser.
I've not tested on android, since for some reason my emulator died. Is it okay to assume the comgooglemaps url scheme to be available? If not, it should also be possible to fall back to an https url.
=> Change map links to deeplinks

lib/blocs/album_list_cubit.dart, lib/blocs/calendar_cubit.dart, lib/blocs/event_admin_cubit.dart, lib/blocs/food_admin_cubit.dart, lib/blocs/member_list_cubit.dart, lib/ui/screens/settings_screen.dart
This fixes a problem where incorrect search results may appear. When an api call was triggered, its result was used even if during the asynchronous gap, something changes such that the result should no longer be used. For example:
- When searching for 'a', a timer is started.
- After 300ms, an http request is sent. 
- Before the corresponding response is received, the user removes the query, so the state should remain loading.
- The response arrives, and handling of the old 'a' search continues, emitting a new incorrect state.
This PR eliminates the problem by discarding a response if the search query has changed. Note that exceptions thrown in the api call will still result in an exception state being emitted.
=> Fix outdated search results

pubspec.lock, pubspec.yaml
photo_view 0.13.0 is not compatible with flutter 2.10.x. The fix (https://github.com/bluefireteam/photo_view/pull/499) has not been released yet. For the time being, we use a reference directly to that commit, rather than the released version. When the fix is released, we should change this back to the new version '0.13.1' or '0.14.0'. I've opened #207 to track that.
=> Use fixed photo_view for flutter 2.10.0

android/app/src/main/AndroidManifest.xml, ios/Podfile.lock, lib/ui/screens/album_screen.dart, lib/ui/screens/event_admin_screen.dart, lib/ui/screens/event_screen.dart, pubspec.lock, pubspec.yaml
Closes #171 
Add a download button to save photos to gallery.
1. Go to photos, open some album
2. view a photo
3. use the download-button in the top-right to save the photo in your gallery
=> Add download button for images

lib/ui/widgets/push_notification_dialog.dart
This prevents exceptions form being thrown when a PushNotificationDialog is shown while the push notification has no title or body.
=> Fix exception on empty pushnotification

lib/ui/widgets/cached_image.dart
Fixes an issue where map images where cached with the same key (that doesnt contain query parameters), leading to all events showing the same map.
=> Fix map image cache keys

lib/api/concrexit_api_repository.dart
Catches some not-so-exceptional exceptions (network stuff) that clutters sentry.
=> Catch HandshakeExceptions

pubspec.lock, pubspec.yaml
This gets rid of the git reference we used while waiting for this update.
See #207.
This may also resolve some out-of-memory crashes related to storing image scale state in long galleries (https://github.com/bluefireteam/photo_view/pull/479).
Closes #206.
=> Update photo_view to 0.14.0

lib/ui/screens/event_admin_screen.dart, lib/ui/screens/food_admin_screen.dart, lib/ui/screens/food_screen.dart
Closes #220.
This handles overflows in food/event admin screens and FoodScreen.
=> Fix admin screen name overflows

lib/blocs/album_cubit.dart, lib/blocs/detail_state.dart, lib/blocs/event_cubit.dart, lib/blocs/food_admin_cubit.dart, lib/blocs/full_member_cubit.dart, lib/blocs/group_cubit.dart, lib/blocs/groups_cubit.dart, lib/blocs/member_cubit.dart, lib/blocs/payment_user_cubit.dart, lib/blocs/registration_fields_cubit.dart, lib/blocs/sales_order_cubit.dart, lib/tosti/blocs/home_cubit.dart, lib/tosti/tosti_screen.dart, lib/ui/screens/album_screen.dart, lib/ui/screens/event_screen.dart, lib/ui/screens/food_admin_screen.dart, lib/ui/screens/food_screen.dart, lib/ui/screens/group_screen.dart, lib/ui/screens/groups_screen.dart, lib/ui/screens/profile_screen.dart, lib/ui/screens/registration_screen.dart, lib/ui/widgets/sales_order_dialog.dart, lib/ui/widgets/tpay_button.dart, test/mocks.mocks.dart, test/widget/tpay_button_test.dart
Closes #321.
This moves the gallery back into a dialog. It also turned out that keeping the initial gallery index in the cubit's state is not necessary. 
Meanwhile, I figured out an (I think) elegant way to change `DetailState` into a class tree. Although I don't really like the `x is Y` syntax being used a lot, I think this reduces the required boilerplate (especially the number of null checks/assertions to enforce non-nullability of results depending on the status) and complexity when extending DetailState (i.e. another non-generic subtype can simply be added).
I think a change like this will help in starting to refactor towards more flexible and conventional classes as they're used e.g. for authentication.
1. Open a gallery.
2. Close it using the …
=> Fix gallery backbutton

.github/workflows/ci.yaml, README.md
Closes #331.
Replaces some hardcoded settings and secrets from the CI workflow with variables.
1. Run the CI
=> Use GHA variables instead of secrets

lib/blocs/groups_cubit.dart, lib/ui/screens/groups_screen.dart
Closes #302.
Added a search function to the groups screen.
1. Go to the groups screen
2. Click on the search button
3. ...
4. Profit
=> Added a search function to the groups screen

lib/ui/screens/event_screen.dart
Closes #343 .
This fixes the message when canceling after the deadline
1. Go to an event that is past the deadline but you are in the queue
2. See message
=> Fix messahe for queue cancelation past the deadline

lib/ui/screens/event_screen.dart
Closes #344 
To some new thalians it was not clear that events like beetfeest still require tickets, because the message seemed to indicate registration.
1. Go to an optional registration event
2. Click on register
=> Make the registered message more clear for optional regs

lib/blocs/groups_cubit.dart, lib/ui/screens/groups_screen.dart
Closes #350 .
Made committee and society groups display in alphabetical order
1. Go to 'GROUPS'.
2. Click on committees or societies.
3. See that it is in alphabetical order.
4. Boards are still from newest to oldest.
=> Made commitee and society groups display in alphabetical order

lib/ui/screens/event_screen.dart
Closes #374 .
Fix pay button displaying when tpay is not allowed.
1. Go to https://staging.thalia.nu/events/180/
2. Click on Register
3.  See that the pay button does not appear
=> Fix pay button displaying when tpay is not allowed

lib/ui/widgets/menu_drawer.dart
Closes #380.
Now instead of closing the app when going back from a screen opened from the menu drawing, it goes to the previous screen.
1. Go to a screen from the menu drawer.
2. Open another screen from the menu drawer.
3. Go back.
4. You're now at the screen you opened first.
=> Fix closing screen opened from menu drawer

lib/models/group.dart, lib/ui/screens/groups_screen.dart
Closes #399.
Displaying current active board in large and also in the list.
Displaying candis in the list as well (and not in large anymore).
1. Go to 'Groups'
2. Click on 'Boards'
=> Display current board

lib/api/concrexit_api_repository.dart, lib/api/exceptions.dart, lib/blocs/member_list_cubit.dart, lib/config.dart, pubspec.yaml
Closes #352 .
This makes the default messages a lot better, especially when not using custom error messages
Not really possible, this is mostly for internal debugging and feedback to users for edge cases
=> Make default error messages better

lib/ui/screens/calendar_screen.dart
Fixes an error that happens when there are no events in the future
There used to be an inconsistency in removing events from up results past and adding them to the down results. This fixes that
1. Go to calendar
2. Click on search
3. Search for something with no events (in the future)
4. See that either there are events, or the screen is black and you cannot scroll up
=> Fix crash oddity when moving events down

lib/ui/screens/event_screen.dart
Closes #434.
Fix the view going back to the top when loading more registrations.
This should ideally be tested with an event with a lot of registrations, but I could not find a way to do this easily.
So instead you can set the `firstPageSize` in the `EventCubit` to 1 and observe the correct behaviour.
=> Fix registration loading in event screen

.github/workflows/ci.yaml, fastlane/Fastfile-Android, fastlane/Fastfile-iOS, integration_test/login_screen_test.dart, lib/api/api_repository.dart, lib/api/concrexit_api_repository.dart, lib/blocs/album_list_cubit.dart, lib/blocs/auth_cubit.dart, lib/blocs/calendar_cubit.dart, lib/blocs/event_admin_cubit.dart, lib/blocs/food_admin_cubit.dart, lib/blocs/groups_cubit.dart, lib/blocs/member_list_cubit.dart, lib/config.dart, lib/main.dart, lib/models/event.dart, lib/routes.dart, lib/ui/screens/album_screen.dart, lib/ui/screens/event_admin_screen.dart, lib/ui/screens/event_screen.dart, lib/ui/screens/login_screen.dart, lib/ui/screens/settings_screen.dart, lib/ui/widgets/cached_image.dart, lib/ui/widgets/tpay_button.dart, lib/utilities/cache_manager.dart, test/mocks.mocks.dart, test/unit/routes_test.dart, test/widget/calendar_test.dart, test/widget/tpay_button_test.dart, test/widget/welcome_test.dart
Closes #457.
This adds a button on the LoginScreen to pick an environment (production, staging or local) from options that depend on variables provided at build-time. That is, in development, only staging will be possible (and default). In CI builds, production will be added and defaulted to. And if you set `--dart-define=LOCAL_THALIA_OAUTH_APP_ID=XXX --dart-define=LOCAL_THALIA_OAUTH_APP_SECRET=XXX`, a local environment is also available (not picked by default), using `http://127.0.0.1:8000`.
I also got rid of a hack we used, removing the navigator around the LoginScreen.
TODO:
1. Make a production build
2. Sign in to production
3. Sign out
4. Sign in to staging
5. If you like, also try a build with local settings
=> Enable picking between concrexit servers

analysis_options.yaml, lib/blocs/album_list_cubit.dart, lib/blocs/calendar_cubit.dart, lib/blocs/list_cubit.dart
Closes #444.
A lot of ListState cubits share a lot of code, and might behave in slightly different ways in some circumstances (like, is it cached, does it propperly do some checks). This PR introduces a class that unifies all common behavior but allows the necessary freedom.
1. Visit all the pages that use a ListState
=> Add a new abstract ListCubit that helps remove a lot of duplicate code

lib/api/api_repository.dart, lib/api/concrexit_api_repository.dart, lib/blocs/event_admin_cubit.dart, lib/models/event_registration.dart, lib/models/event_registration.g.dart, lib/ui/screens/event_admin_screen.dart, pubspec.lock, test/mocks.mocks.dart
Closes #179.
Added `queued` filter to API AdminEventRegistration request.
Added lists of `AdminEventRegistration`s `queuedRegistrations` and `cancelledRegistrations` to `EventAdminState` and `EventAdminCubit`.
Turned the `EventAdminScreen` into a screen with tabs, and gave queued and cancelled registrations their own type of tiles with useful info.
1. Go to any event.
2. Click on the gear icon to go to admin view.
Search in its current form still only searches regular registrations.
I think this is OK as this is the most relevant use of search, and I want to avoid double work because of #427.
=> Cancelled and queued registrations in admin screen

lib/blocs/event_admin_cubit.dart, lib/ui/screens/event_admin_screen.dart
This should be handled by the cubit as it is in other cubits, not in the screen. At least that is how it is now.
=> Rework how the error messages work for event admin

.github/workflows/ci.yaml, pubspec.yaml
This adds a build cache to (for now) integration testing on IOS
=> Add build cache

lib/ui/screens/event_screen.dart, lib/ui/screens/food_screen.dart
Closes #505 .
When the food event ends, it is no longer possible to press the order button
1. Go to a food order event
2. Wait for the event to end
=> Update the food event to grey out when it is passed

lib/routes.dart
The deeplink /groups/{boards/...} would get interpreted as a group with pk {boards/...}. This would obviously not work and crash the app.
Closes #452.
1. Go to a page of a group on the website
2. Open in app
3. Observe it not crashing
=> Fixed an issue with deeplinks

lib/ui/screens/profile_screen.dart
Closes #330.
This makes sure we do not emit stated after the profile page has been closed
Somehow open a different page while it is uploading a picture
=> Don't reload the profile when the profile has been closed

lib/ui/widgets/cached_image.dart, lib/ui/widgets/gallery.dart
Closes #458 
Previously, you could zoom out on a photo in an album and it would stay zoomed out. 
Furthermore, photos are not cached correctly, so when you open a photo and scroll to the next one, the loading time is annoyingly long.
1. Go to an album with a couple of photos so you can scroll a couple of times
2. Click on an image (I'd do the first one so you can scroll more)
3. Scroll a couple of times and the loading time will be a lot smaller. You can also zoom out and the photo will go back to the original size instead of a zoomed-out size.
=> Faster image scrolling and fix zoom out issue

lib/blocs/food_cubit.dart, lib/models/food_event.dart, lib/ui/screens/food_screen.dart
Closes #516.
This makes sure that the prices are always visible by putting them on the right hand size
1. Go to a food event
2. Click on see the prices always being possible
=> Make sure that the food prices are always visible

lib/api/concrexit_api_repository.dart, lib/blocs/auth_cubit.dart, lib/blocs/list_cubit.dart
This should shut sentry up about a lot of issues that we actually handle correctly
=> Make sentry not report exceptions from the HTTP client

lib/ui/widgets/cached_image.dart, lib/ui/widgets/gallery.dart
Closes #403.
The previous likePhoto function is actually a function that toggles the like, so I changed it to toggleLikePhoto. I added a function that will like the photo even if the photo has already been liked. This function is called after a double-tap
1. Go to any album
2. Click on some photo
3. Double-tap the photo. If should receive a like. Double-tap again and see that the photo is still liked.
4. You can test that you can like and unlike the photo by tapping the heart icon on the bottom of the screen
=> Double-click unlikes is odd
