svthalia/Reaxit

ios/Podfile.lock
lib/config.dart
lib/main.dart
pubspec.lock
pubspec.yaml

The DSN can be set through a --dart-define at build-time:
`flutter run --dart-define=SENTRY_DSN="https://xxx@yyy.ingest.sentry.io/zzz"`
Closes #30.

Add Sentry

---

lib/blocs/api_repository.dart
lib/blocs/registration_fields_cubit.dart
lib/models/registration_field.dart
lib/models/registration_field.g.dart
lib/ui/screens/registration_screen.dart

Registration fields

---

android/app/src/main/AndroidManifest.xml
ios/Podfile.lock
ios/Runner/Info.plist
lib/blocs/api_repository.dart
lib/blocs/auth_bloc.dart
lib/blocs/full_member_cubit.dart
lib/blocs/member_list_bloc.dart
lib/ui/router/router.dart
lib/ui/screens/login_screen.dart
lib/ui/screens/profile_screen.dart
lib/ui/screens/registration_screen.dart
pubspec.lock
pubspec.yaml

Closes #15
Adds buttons and field to edit profile picture and description.

Edit profile

---

ios/Podfile.lock
lib/blocs/album_cubit.dart
lib/blocs/api_repository.dart
lib/models/album.dart
lib/models/album.g.dart
lib/models/photo.dart
lib/models/photo.g.dart
lib/ui/router/router.dart
lib/ui/screens/album_screen.dart
lib/ui/widgets/album_tile.dart
pubspec.lock
pubspec.yaml

Add share buttons

---

lib/blocs/api_repository.dart
lib/blocs/event_cubit.dart
lib/models/event_registration.dart
lib/models/event_registration.g.dart
lib/ui/screens/event_screen.dart

Reflect changes in the API

---

.github/workflows/codestyle.yaml

This PR adds a workflow that checks the formatting of the code as specified by flutter.
1. Check that the workflow passes

Add codestyle workflow

---

.github/ISSUE_TEMPLATE/other.md

Fix naming in other template

---

android/app/src/main/AndroidManifest.xml

Closes #75
Remove label for the oauth callback in android
1. Try to login into the app
2. Make sure you have multiple apps accepting the url
3. See the name that is shown

Remove label for the oauth callback in android

---

lib/ui/screens/calendar_screen.dart
lib/ui/screens/food_screen.dart
lib/ui/widgets/event_detail_card.dart

Fix timezones

---

android/app/build.gradle
android/build.gradle
ios/Runner/Info.plist
lib/blocs/member_list_bloc.dart
lib/ui/router.dart

Closes #68.
Also adds the firebase configuration for android.

Fix app name vars

---

lib/ui/screens/profile_screen.dart

Closes #ISSUE
study programme and cohort are now below each other instead of besides.
1. view someone's profile page

Moved the cohort field to a new line below study programme.

---

lib/push_notifications.dart

Catch unexpected firebase exceptions

---

lib/ui/screens/event_screen.dart

Adds a button to order food to the event screen if there's a food event.
1. Go to an event with pizza
2. Click on 'ORDER FOOD'
3. Order a pizza

Add order-food-button to event screen

---

lib/models/album.g.dart
lib/models/device.g.dart
lib/models/event.g.dart
lib/models/event_registration.g.dart
lib/models/food_event.g.dart
lib/models/food_order.g.dart
lib/models/frontpage_article.g.dart
lib/models/list_response.g.dart
lib/models/member.dart
lib/models/member.g.dart
lib/models/payable.g.dart
lib/models/payment.g.dart
lib/models/payment_user.g.dart
lib/models/photo.g.dart
lib/models/product.g.dart
lib/models/push_notification_category.g.dart
lib/models/registration_field.g.dart
lib/models/slide.g.dart
lib/ui/screens/event_screen.dart
lib/ui/screens/profile_screen.dart
lib/ui/widgets/album_tile.dart
lib/ui/widgets/member_tile.dart

Closes #133.
- Remove the OpenContainer animation from album tiles.
- Refactor gradients to be const.
- Add ink effects to member/album tiles.
- Move membertile for non-members from eventscreen to member_tile.
Regarding 'The grid is still not consistent...', I know, I also did not expect a larger image to show a larger part of the original...  It fills more of the screen with relevant content. We've compared last monday and chosen to go for the smaller gutters.

Refactor tiles

---

lib/ui/screens/profile_screen.dart

Closes #130.
Adds the buttons for changing profile pictures to the AppBar of the profile screen, and replaces the used icons. Together with #144 this solves most items in #130, except for:
- The spacing of the name is different from the other text in the screen
- Some information is in cards for no clear reason. It would be better if all the content would be equal and thus on the same level.
We've discussed these. The name's spacing is different because it needs to match all other appbars. The cards are there to group related content. It's true that it's different from the other content items, but the content itself is also different. Some visual clue is needed to group them.

Add photo edit button to profile outside modal

---

lib/api_repository.dart
lib/blocs/event_admin_cubit.dart

Fix cancelled registrations in event admin

---

lib/blocs/event_admin_cubit.dart

Would close #166, but we leave the issue open waiting for API changes.
Filter queued people being shown in admin panel. 
Done by filtering in the Cubit. Should be removed when API is updated.
1. Have an event with people on the waiting list
2. See if event admin shows these people
3. Reload to see if they're still filtered

Fix queued registrations being shown

---

lib/ui/screens/event_screen.dart

Closes #176.
Test by trying to share an event.

Add event share button

---

android/app/src/main/AndroidManifest.xml
lib/api_repository.dart
lib/push_notifications.dart
lib/ui/router.dart
lib/ui/screens/calendar_screen.dart
lib/ui/screens/event_screen.dart
lib/ui/screens/profile_screen.dart
lib/ui/screens/settings_screen.dart
lib/ui/screens/welcome_screen.dart

Closes #172.
Test by opening opening a Link (such as the changelog button in settings) on a recent android device/emulator (api level 30).

Fix Links on android

---

lib/ui/screens/event_screen.dart

Closes #165 
Added weekday to all dates in the event detail. Looks like this:
1. Go to event detail
2. Check how start date, end date, registration start, registration deadline, cancellation deadline look.

Add weekday to event detail

---

.github/workflows/build.yaml
.github/workflows/codestyle.yaml
.github/workflows/deploy.yaml

Updates `subosito/flutter-action` to v2, and uses the new support for `actions/cache` to speed up the workflows.
1. Run the workflows and see that they still work, and are faster.

Use actions/cache for flutter

---

.github/workflows/build.yaml
.github/workflows/codestyle.yaml
.github/workflows/deploy.yaml
android/app/build.gradle
android/build.gradle
ios/Podfile.lock
lib/ui/theme.dart
pubspec.lock
pubspec.yaml

Updates to flutter 2.10.0.
This includes upgrading some packages.

Update flutter to 2.10.0

---

lib/api/api_repository.dart
lib/api/concrexit_api_repository.dart
lib/blocs/food_admin_cubit.dart
lib/models/event_registration.dart
lib/models/event_registration.g.dart
lib/models/food_order.dart
lib/models/food_order.g.dart
lib/models/member.dart
lib/models/member.g.dart
lib/ui/screens/event_admin_screen.dart
lib/ui/screens/food_admin_screen.dart
pubspec.lock
pubspec.yaml

Closes #163.
Adds AdminListMember and AdminFoodOrder using the changes in concrexit#2166 and concrexit#2049. Let's not merge this PR before concrexit#2166 is released.
Try out the event and food admins, and verify that firstname and lastname are shown, not displayName.

Show true name in admins

---

lib/ui/screens/event_screen.dart

Fix not refreshing registrations on eventscreen

---

lib/routes.dart

Closes #203 
Fixes exception upon updating registration information
1. Go to an event with registration information fields
2. Click on 'UPDATE REGISTRATION'

Fixed incompatable types

---

lib/routes.dart
lib/ui/screens/event_screen.dart

Fix bug in navigation to event registration screen

---

lib/ui/screens/event_screen.dart
lib/ui/screens/welcome_screen.dart

This handles deep links in event descriptions correctly.

Check for deeplinks in all HtmlWidgets

---

lib/api/concrexit_api_repository.dart

Part of #99.
This prevents skipping frames because of expensive parsing of JSON lists from the API.

Parse lists in isolates

---

analysis_options.yaml
lib/ui/screens/album_screen.dart
lib/ui/screens/event_admin_screen.dart
lib/ui/screens/event_screen.dart
lib/ui/screens/food_admin_screen.dart
lib/ui/screens/food_screen.dart
lib/ui/screens/profile_screen.dart
lib/ui/screens/registration_screen.dart
lib/ui/screens/settings_screen.dart
lib/ui/screens/welcome_screen.dart
lib/ui/widgets/tpay_button.dart

Closes #228.
See https://www.youtube.com/watch?v=bzWaMpD1LHY for more information.

Refactor asynchronous uses of buildcontext

---

lib/routes.dart
test/unit/routes_test.dart

This makes the app handle /members/photos/ as deeplink to the albums list.

Add /members/photos/ deeplink

---

README.md
ios/Runner.xcodeproj/project.pbxproj
lib/api/api_repository.dart
lib/api/concrexit_api_repository.dart
lib/blocs.dart
lib/blocs/event_admin_cubit.dart
lib/blocs/mark_present_cubit.dart
lib/models/event.dart
lib/models/event.g.dart
lib/routes.dart
lib/ui/screens/event_admin_screen.dart
lib/ui/widgets.dart
lib/ui/widgets/mark_present_dialog.dart
pubspec.lock
pubspec.yaml
test/mocks.mocks.dart
test/unit/routes_test.dart

Closes #257.
Adds a dialog similar to that in #238 that handles the mark present url as deeplink, and an appbar action to display the presence QR code from the event admin screen.
1. Be an organizer and show a QR code.
2. Scan such a code (or actually force to open it as deeplink with thaliapp:// scheme).

Add mark-present-url deeplink and qr rendering

---

android/app/src/main/AndroidManifest.xml
ios/Podfile.lock
lib/blocs/auth_cubit.dart
lib/tosti/blocs/auth_cubit.dart
pubspec.lock
pubspec.yaml

Upgrade to flutter_web_auth_2

---

lib/ui/screens/food_screen.dart

This is ugly:
I hope this makes it full width.

Fix pay button width on FoodScreen

---

lib/tosti/blocs/home_cubit.dart
lib/tosti/models/shift.dart
lib/tosti/models/shift.g.dart
lib/tosti/models/venue.dart
lib/tosti/models/venue.g.dart
lib/tosti/tosti_shift_screen.dart

After this I hope the TOSTI client works again.
Just updates models to match some API changes.
1. Go to a tosti shift, order, etc.

Adapt to changes to the TOSTI api

---

lib/ui/screens/profile_screen.dart

Closes #303.
When clicking on on an achievement it either opens the group or the url. If neither are provided do nothing.
1. Go to you rpofile
2. Click on an achievement
3. See that the group opens
4. Click on a mentor achievement and see nothing happens

Make achievements in the profile screen link to their respective group or url

---

lib/blocs/welcome_cubit.dart
lib/ui/screens/welcome_screen.dart
lib/ui/widgets/event_detail_card.dart
test/mocks.dart
test/mocks.mocks.dart
test/widget/welcome_test.dart

Closes #385.
Shows external events on welcome screen.
1. Go to welcome screen.
2. See that external evets are shown.

Show external events on welcome screen

---

lib/api/concrexit_api_repository.dart
lib/blocs/auth_cubit.dart

Closes #418.
In debug mode for all API requests the url and response code, or exception will be logged to the console.
1. Start app in debug mode.
2. See all request logged in the console.

Add api request logging in debug mode

---

lib/config.dart
pubspec.yaml

Bump app version number

---

.github/workflows/ci.yaml
analysis_options.yaml
lib/ui/screens/settings_screen.dart
lib/ui/widgets/mark_present_dialog.dart
pubspec.lock
pubspec.yaml

This bumps flutter and dart, and the app version numper

Bump flutter and dart + version

---

lib/ui/screens/calendar_screen.dart
lib/ui/widgets/events.dart
test/unit/calendar_test.dart

Closes #451 .
A small refactor of the code that adds today to the calendar, while also adding some comments.
Although it is very difficult to test the original issue ,there is a new test which passes with the new changes (and not before). This test likely represents the original issue

Fix calendar not adding a day for today if there are no later events

---

lib/ui/screens/welcome_screen.dart
lib/ui/widgets/event_detail_card.dart

These used to be black (on a black background), this makes them white
1. Open staging _today_
2. look at the homescreen

Fix the colors of external events on the homescreen

---

lib/blocs/detail_state.dart
lib/ui/screens/group_screen.dart

Closes #471.
Add email to all group screens
1. Go to groups
2. Click on a group
3. Click on the email link

Add email link for groups

---

lib/blocs/event_cubit.dart
lib/config.dart
lib/ui/screens/event_screen.dart
lib/ui/widgets/tpay_button.dart

Closes #455 .
This debounces the thaliapay button, showing it disabled in the mean time
1. Go to any page to thalia
2. pay and see it grayed out.

Debounce thaliapay

---

lib/blocs/detail_state.dart
lib/models/payment.dart
lib/ui/screens/event_admin_screen.dart
lib/ui/screens/food_admin_screen.dart
lib/ui/screens/profile_screen.dart
lib/ui/screens/registration_screen.dart
lib/ui/widgets.dart
lib/ui/widgets/app_bar.dart
lib/ui/widgets/error_center.dart
lib/ui/widgets/filter_popup.dart
lib/ui/widgets/sortbutton.dart

Closes #168.
Add filters and orderings in event admin view
1. Go to events
2. Click on settings icon
3. click on filter

Add option to filter and sort registrations in admin view

---

lib/blocs/calendar_cubit.dart

This is an off-by-one error that breaks tests on the first of the month

Fix calendar cubit off-by-one

---

integration_test/album_screen_test.dart
lib/ui/screens/album_screen.dart
lib/ui/screens/event_admin_screen.dart
lib/ui/screens/event_screen.dart
lib/ui/widgets/app_bar.dart
lib/ui/widgets/filter_popup.dart
lib/ui/widgets/sortbutton.dart
test_driver/integration_test.dart

Closes #495 #454
1. Go to albums
2. Go to filter registrations

Fix capitals

---

lib/models/event_registration.dart
lib/ui/screens/event_admin_screen.dart
lib/ui/widgets/app_bar.dart
lib/ui/widgets/filter_popup.dart

Closes #485.
This rework fixed a couple issues:
- spelling
- ordering (and filtering) for payment type on free events
-  name ordering does not work
1. Go to scarletto event
2. Check that ordering/filtering no longer shows payment things
3. Check name sorting works

Slight rework of the event admin screen

---

integration_test/calendar_screen_test.dart
lib/blocs/album_list_cubit.dart
lib/blocs/calendar_cubit.dart
lib/blocs/groups_cubit.dart
lib/blocs/list_cubit.dart
lib/blocs/member_list_cubit.dart
lib/blocs/thabloid_list_cubit.dart
lib/ui/screens/calendar_screen.dart
lib/ui/screens/groups_screen.dart
lib/ui/screens/thabloids_screen.dart

Combine all list-like cubits to be `ListCubit`s, making implementing them easier and more uniform
Go to any page with a list

Convert listcubit

---

README.md
lib/api/api_repository.dart
lib/api/concrexit_api_repository.dart
lib/blocs/list_cubit.dart
lib/blocs/member_list_cubit.dart
lib/models/event.g.dart
lib/ui/screens/calendar_screen.dart
lib/ui/screens/members_screen.dart
lib/ui/theme.dart
test/mocks.mocks.dart

Closes #509 
1. Go to member list
2. Click on a year

Add year filtering

---

lib/ui/widgets/menu_drawer.dart

This makes sure it actually becomes magenta and has a nicer icon

Fix the thabloids drawer

---

lib/blocs/event_cubit.dart

Difficult to test, hopefully things will chill out at sentry a bit

This should fix a lot of emit after close issues

---

lib/api/api_repository.dart
lib/api/concrexit_api_repository.dart
lib/blocs/thabloid_cubit.dart
lib/blocs/thabloid_list_cubit.dart
lib/main.dart
lib/ui/screens/thabloids_screen.dart
lib/ui/widgets/thabloid_tile.dart

This makes a cubit for each thabloid that refreshes the URL after an hour
Closes #517.
This fixes the thabloid URLs expiring
1. Go to thabloids
2. Wait for an hour
3. Check that it works

Change how the thabloids work

---

android/app/build.gradle
android/app/proguard-rules.pro
pubspec.lock
pubspec.yaml

1. Go to profile
2. Click on new picture
3. Complete to ucrop
4. See it works and the buttons are pressable

Bump ucrop and add ucrop and others to exceptions

---

lib/blocs/list_cubit.dart

Closes #ISSUE.
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'

Fix crash when results are empty

---

lib/api/concrexit_api_repository.dart
lib/blocs/auth_cubit.dart
lib/ui/screens/settings_screen.dart

Add breadcrumbs to debug unauthorised issue

---

android/app/build.gradle
android/app/proguard-rules.pro
lib/blocs/auth_cubit.dart
pubspec.lock
pubspec.yaml

Use cupertino http

---

.github/workflows/ci.yaml
ios/Podfile

Closes #ISSUE.
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'

Fix podfile

---

lib/main.dart
lib/ui/widgets/push_notification_overlay.dart

This should prevent app crashes sometimes when opening notifications

This should at least reduce the spam in sentry
